version: "3.3"

services:
  mongo:
    container_name: mongo
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
  
  api-service:
    container_name: api-service
    image: 'learn_api_v2'
    ports:
      - "8000:80"



volumes:
  mongodb_data:
    driver: local